GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzI2NDk1MTUwfQ.ZuHHMl8qZJykxwiZVDJbBHj0JNCcx8NLzLnN24hW7uU

###

GET http://localhost:3000/profile/ 
Authrization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNzI2NDk1MTUwfQ.ZuHHMl8qZJykxwiZVDJbBHj0JNCcx8NLzLnN24hW7uU

GET http://localhost:3000/books/1/

###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}